name: Build and compile

on:
  push:
    branches:
      - dev
      - snark_wrapper
  pull_request:
    branches:
      - dev
      - snark_wrapper

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [self-hosted, ci-runner]

    steps:
      - uses: actions/checkout@v3
      - name: Setup rustup
        run: |
          wget -q -O - https://sh.rustup.rs | bash -s -- -y
          echo "${HOME}/.cargo/bin" >> "${GITHUB_PATH}"
          echo "CARGO_BUILD_JOBS=$(($(nproc) /2))" >> "${GITHUB_ENV}"
          echo "export PATH=\"$HOME/.cargo/bin:\$PATH\"" >> "${HOME}/.bash_profile"
      - name: Setup rust
        run: |
          rustup set profile minimal
          rustup toolchain install nightly-2023-08-23
          rustup default nightly-2023-08-23
      - name: Install build dependencies
        run: |
          sudo apt update && sudo apt install -y pkg-config libssl-dev libclang-dev gcc g++
      - name: Compile
        run: |
          cargo build --verbose
